version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      timeout: 4s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  backend:
    build: .
    environment:
      DATABASE_URL: postgres://app:app@db:5432/appdb
      JWT_SECRET: devsecretdevsecretdevsecret123456
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin1234567890
      STORAGE_PROVIDER: local
      MEDIA_LOCAL_DIR: /app/backend/uploads
      PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/backend/uploads
    ports:
      - "8080:8080"

volumes:
  db_data:
  minio_data:
