version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: community-backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      DATABASE_URL: "file:./dev.db"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/prisma:/app/prisma:ro
    command: ["node", "dist/server.js"]
    # For hot reload in dev you could switch to: npm run dev (needs nodemon)