// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndyfjabavsvzdasqtrux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5keWZqYWJhdnN2emRhc3F0cnV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDQyOTcsImV4cCI6MjA3MTI4MDI5N30.Q4Vp8vOX_0d3cd2YGQadqz819bTdeX0ttsLHobsIXQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});