name: Update Roma Matches JSON

on:
  schedule:
    # Daily full refresh at 6:00 AM UTC
    - cron: '0 6 * * *'
    # More frequent updates during European evening hours (18:00-22:00 UTC)
    # Every 30 minutes between 18:00 and 22:00 UTC (conservative rate limiting)
    - cron: '0,30 18-22 * * *'
  
  workflow_dispatch: # Allow manual triggering

jobs:
  update-matches:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Update Roma matches JSON
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          ROMA_TEAM_ID: 497
          SEASON: 2025
        run: |
          npm run update-roma-matches
          # Also update the public directory copy for build distribution
          cp data/roma-matches.json public/data/roma-matches.json
        
      - name: Check for changes
        id: verify-changed-files
        run: |
          if git diff --quiet data/roma-matches.json public/data/roma-matches.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/roma-matches.json public/data/roma-matches.json
          git commit -m "chore: update Roma matches data [skip ci]"
          git push
          
      - name: Log completion
        run: |
          if [ "${{ steps.verify-changed-files.outputs.changed }}" == "true" ]; then
            echo "✅ Roma matches data updated successfully"
          else
            echo "📊 No changes detected - matches data already up to date"
          fi